### ISSUE TITLE
[request] README.md를 구성해 주세요.

### ISSUE THREAD

**Issue by hyunsung-kim** [area363/baseballGM#1]
Description
Features
Contributor
License

이러 항목이라도 간단하게 프로젝트를 설명해 주는 부분이 있으면 좋을 거 같습니다.

**Comment by area363** [comment]
넵 간단하게 작성하였고 프로젝트 진행되면서 계속 업데이트 하겠습니다.

**Comment by hyunsung-kim** [comment]
좋습니다. 수고하셨어요
